// @ts-ignore
import { textToMarker } from "./leaflet/markers";
import { MapInterface } from "./MapInterface";
import "./leaflet/realtime";
import type { Config, ClusterStyle } from "./types";
import { addCss, addTransparentBackground, createDefaultPopup } from "./utils";

declare global {
  namespace L {
    var realtime: any;
    var Realtime: any;
  }
}

//Add the style of the loader
addCss(
  `.loader{border:16px solid #f3f3f3;border-top:16px solid #3498db;border-radius:50%;width:60px;height:60px;left:0;right:0;top:0;margin:auto;bottom:0;position:fixed;animation:spin 2s linear infinite}@keyframes spin{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}`,
);

//Layer that represents all count circles and tooltips
let countLayer: any;
let geojsonLayer: any;
//Extend a LayerGroup
const STAMLayer = L.LayerGroup.extend({
  initialize: function (config: Config) {
    const mapInterface = new MapInterface(config);

    let highlight: any;

    let cache: any = {
      type: "FeatureCollection",
      features: [],
    };

    //Default style
    const style = {
      default: {
        opacity: 0,
        fillOpacity: 0,
      },
      highlight: {
        color: "red",
        opacity: 1,
      },
    };

    //Used for setting the style of a polygon when it is hovered
    const setHighlight = function (layer: any) {
      // Check if something's highlighted, if so unset highlight
      if (highlight) {
        unsetHighlight(highlight);
      }

      //Get the style from the config
      const configStyle =
        typeof config.clusterStyle == "function"
          ? ((feature: any) => {
              if (!feature._clusterStyleCache) {
                feature._clusterStyleCache = {
                  style: config.clusterStyle(feature),
                };
              }
              return feature._clusterStyleCache.style?.polygon.hover;
            })(layer.feature)
          : (config.clusterStyle as ClusterStyle)?.polygon.hover;

      //Add a transparent background, if no background was set
      addTransparentBackground(configStyle);

      // Set highlight style on layer and store to variable
      layer.setStyle(configStyle ?? style.highlight);
      highlight = layer;
    };

    //Remove the style after the mouse hovered over a polygon
    const unsetHighlight = function (layer: any) {
      //Get the style from the config
      const configStyle =
        typeof config.clusterStyle == "function"
          ? ((feature: any) => {
              if (!feature._clusterStyleCache) {
                feature._clusterStyleCache = {
                  style: config.clusterStyle(feature),
                };
              }
              return feature._clusterStyleCache.style?.polygon.default;
            })(layer.feature)
          : (config.clusterStyle as ClusterStyle)?.polygon.default;

      //Add a transparent background, if no background was set
      addTransparentBackground(configStyle);

      // Set default style and clear variable
      layer.setStyle(configStyle ?? style.default);
      highlight = null;
    };

    let initialBounds: any = null;

    //Called when the layer is added to the map
    this.on("add", function (this: any) {
      if (this._map != undefined) {
        const map = this._map;

        let zoom = map.getZoom();

        countLayer = L.layerGroup();

        //Called on every feature of the map
        const onEachFeature = (feature: any, layer: any) => {
          //Check if a polygon is cluster generated by the library and a polygon
          if (feature.geometry?.type == "Polygon" && feature.properties.count) {
            //Check for mouse hover
            layer.on("mouseover", function () {
              if (config.clusterMouseOver) config.clusterMouseOver(feature);

              //Highlight the polygon with the given style
              setHighlight(layer);
            });

            layer.on("mouseout", function () {
              unsetHighlight(layer);
            });

            layer.on("click", function () {
              //Configure a click on the cluster, if nothing is configured or nothing returned, the map zooms to the bounds of the polygon
              if (config.clusterClick) {
                return config.clusterClick(feature);
              }
              map.fitBounds(layer.getBounds());
            });

            //Get the style from the config
            const configStyle =
              typeof config.clusterStyle == "function"
                ? ((feature: any) => {
                    if (!feature._clusterStyleCache) {
                      feature._clusterStyleCache = {
                        style: config.clusterStyle(feature),
                      };
                    }
                    return feature._clusterStyleCache.style?.polygon.default;
                  })(layer.feature)
                : (config.clusterStyle as ClusterStyle)?.polygon.default;

            //Add a transparent background, if no background was set
            addTransparentBackground(configStyle);

            //Set the default style of a polygon
            layer.setStyle(configStyle ?? style.default);

            //Get the bounds and calculate the center of the polygon
            const bounds = layer.getBounds();
            const lat = (bounds._northEast.lat + bounds._southWest.lat) / 2;
            const lng = (bounds._northEast.lng + bounds._southWest.lng) / 2;

            //Position a circle in the center
            const circle = L.circleMarker(L.latLng(lat, lng), {
              radius: 127 / 3,
            });

            //Add the count of things inside the polygon to the circle
            circle.bindTooltip(`<span>${feature.properties.count}</span>`, {
              permanent: true,
              direction: "center",
              className: "count",
            });

            //Add the circle to the countLayer
            countLayer.addLayer(circle);
          } else {
            let defaultPopup: boolean = true;

            //Add a click event to the markers
            layer.on("click", function () {
              //Get view before opening popup
              initialBounds = map.getBounds();
              if (!layer.getPopup()) {
                //Bind popup with functions return if present
                if (config.markerClick) {
                  feature.properties.closeMarker = () => {
                    layer.bindPopup(out).closePopup();
                  };
                  const out = config.markerClick(feature);
                  if (out) {
                    defaultPopup = false;
                    layer.bindPopup(out).openPopup();
                  }
                }

                if (defaultPopup) {
                  //Default behavior
                  const div = document.createElement("div");
                  createDefaultPopup(div, feature, config);
                  layer.bindPopup(div).openPopup();
                }
              } else {
                //markerClick is only called the first time a marker has been clicked
                //config.markerClick(feature);
                layer.getPopup().openPopup();
              }
            });

            layer.on("popupclose", function () {
              if (initialBounds) {
                map.fitBounds(initialBounds);
              }
              if (config.popupClose) {
                config.popupClose(feature);
              }
            });

            layer.on("mouseover", function () {
              if (config.markerMouseOver) return config.markerMouseOver(feature);
            });
          }
        };

        //Used for marker styling
        const pointToLayer = function (feature: any, latlng: any) {
          if (typeof config.markerStyle == "function") {
            const color = config.markerStyle(feature);
            //A style function may return the color directly or as a promise
            if (color instanceof Promise) {
              const marker = L.marker(latlng);
              //Set the icon once the color resolves
              color.then((resolved: string) => marker.setIcon(textToMarker(resolved)));
              return marker;
            }
            return L.marker(latlng, { icon: textToMarker(color) });
          }

          //Marker coloring
          return L.marker(latlng, {
            icon:
              typeof config.markerStyle == "string"
                ? textToMarker(config.markerStyle)
                : new L.Icon.Default(),
          });
        };

        // The polygonStyle should only be applied to Locations for Features from the STA service
        // not to generated squares
        let styleFunction: any = undefined;
        if (typeof config.polygonStyle == "function") {
          styleFunction = (feature: any) => {
            if (feature.geometry?.type == "Polygon" && feature.properties.count) {
              return undefined;
            }

            if (!feature._polygonStyleCache) {
              //Add to object to prevent recall, if style function returns undefined
              feature._polygonStyleCache = {
                style:
                  typeof config.polygonStyle === "string"
                    ? config.polygonStyle
                    : (config.polygonStyle as Function)(feature),
              };
            }

            return feature._polygonStyleCache.style;
          };
        } else if (config.polygonStyle) {
          styleFunction = function (feature: any) {
            if (feature.geometry?.type == "Polygon" && feature.properties.count) {
              return undefined;
            }
            return config.polygonStyle;
          };
        }

        //Called when the LayerGroup was added to the map, then the LayerGroup's super class is done initiating
        map.on("layeradd", function (this: any) {
          map.off("layeradd");

          //Create a geojson layer
          geojsonLayer = L.realtime(
            function (resolve: any, reject: any) {
              resolve(cache);
            },
            {
              onEachFeature,
              pointToLayer,
              getFeatureId: function (geojson: any) {
                //Prevent style reset
                if (highlight) setHighlight(highlight);
                //Return id if possible
                if (geojson.properties["@iot.id"]) return geojson.properties["@iot.id"];

                const flatten = geojson.geometry.coordinates.flat(3);
                if (geojson.properties.count) {
                  return flatten.join("/");
                } else {
                  //Create id from coordinates
                  return `${flatten[0]}/${flatten[1]}`;
                }
              },
              style: styleFunction,
              interval: 500,
            },
          );

          //Add count and geojson layer
          this.addLayer(countLayer);
          this.addLayer(geojsonLayer);

          //Initiate the layer group with the current bounds and zoom level
          const bounds = map.getBounds();
          mapInterface.getLayerData(map.getZoom(), [
            bounds._northEast.lng,
            bounds._northEast.lat,
            bounds._southWest.lng,
            bounds._southWest.lat,
          ]);
        });

        mapInterface.onChange((geojson: any) => {
          if (geojson.zoom == zoom) {
            cache = geojson;
          }
        });

        //Called when zoom ended or the map was moved. The geojson layer is removed and a new one added, because the loaded geojson's are cached inside the MapInterface
        map.on("moveend", function () {
          //Update the zoom variable if the zoom was changed
          if (zoom != map.getZoom()) {
            zoom = map.getZoom();
            countLayer.clearLayers();
          }
          //Set flag to true so that the cluster labels are removed
          const bounds = map.getBounds();

          //add a new layer and remove all old layers
          mapInterface.getLayerData(map.getZoom(), [
            bounds._northEast.lng,
            bounds._northEast.lat,
            bounds._southWest.lng,
            bounds._southWest.lat,
          ]);
        });
      }
    });
  },
}) as any;

const STAM = function (config: Config) {
  return new STAMLayer(config);
};

export { STAM };

//Adding custom css to head, so that the count tooltipp's background is transparent
addCss(
  ".leaflet-tooltip.count {background-color: transparent;border: transparent;  box-shadow: none;  font-weight: bold;font-size: 20px;}",
);
