name: Test and Release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-release:
    name: Run tests and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/setup@v1
        name: Install Node.js and pnpm
        with:
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm format:check
      - name: Run tests
        run: pnpm test
      - name: Run typecheck
        run: pnpm typecheck
      - name: Run build
        run: pnpm build
      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
